global using Phoenix.WebClient.Services;
global using Phoenix.Infrastructure;
global using Phoenix.Models.Shared;
global using Phoenix.Services;
global using Microsoft.AspNetCore.Components;
global using Phoenix.Shared;
global using Microsoft.AspNetCore.Components.Forms;
global using Microsoft.JSInterop;
global using System.ComponentModel.DataAnnotations;